services:
  nuvioweb:
    container_name: nuvioweb
    build:
      context: .
      args:
        NUVIO_SUPABASE_URL: ${NUVIO_SUPABASE_URL:-}
        NUVIO_SUPABASE_ANON_KEY: ${NUVIO_SUPABASE_ANON_KEY:-}
        NUVIO_SUPABASE_FALLBACK_URL: ${NUVIO_SUPABASE_FALLBACK_URL:-}
        TV_LOGIN_WEB_BASE_URL: ${TV_LOGIN_WEB_BASE_URL:-}
        YOUTUBE_PROXY_URL: ${YOUTUBE_PROXY_URL:-youtube-proxy.html}
        INTRODB_API_URL: "${INTRODB_API_URL:-https://api.introdb.app/}"
        IMDB_RATINGS_API_BASE_URL: ${IMDB_RATINGS_API_BASE_URL:-}
        IMDB_TAPFRAME_API_BASE_URL: ${IMDB_TAPFRAME_API_BASE_URL:-}
        AVATAR_PUBLIC_BASE_URL: ${AVATAR_PUBLIC_BASE_URL:-}
        UNIQUE_CONTRIBUTIONS_BASE_URL: ${UNIQUE_CONTRIBUTIONS_BASE_URL:-}
        DONATIONS_BASE_URL: ${DONATIONS_BASE_URL:-}
        DONATIONS_DONATE_URL: ${DONATIONS_DONATE_URL:-}
        SPONSOR_NAMES: ${SPONSOR_NAMES:-ragmehos.}
        TMDB_API_KEY: ${TMDB_API_KEY:-}
        TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID:-}
        SIMKL_CLIENT_ID: ${SIMKL_CLIENT_ID:-}
        SIMKL_APP_NAME: ${SIMKL_APP_NAME:-nuvio}
        PREMIUMIZE_CLIENT_ID: ${PREMIUMIZE_CLIENT_ID:-}
    ports:
      - "4173:80"
    restart: unless-stopped
