services:
  nuvioweb:
    container_name: nuvioweb
    build:
      context: .
    environment:
      NUVIO_SUPABASE_URL: ${NUVIO_SUPABASE_URL:-}
      NUVIO_SUPABASE_ANON_KEY: ${NUVIO_SUPABASE_ANON_KEY:-}
      NUVIO_SUPABASE_FALLBACK_URL: ${NUVIO_SUPABASE_FALLBACK_URL:-}
      YOUTUBE_PROXY_URL: ${YOUTUBE_PROXY_URL:-youtube-proxy.html}
      INTRODB_API_URL: "${INTRODB_API_URL:-https://api.introdb.app/}"
      IMDB_RATINGS_API_BASE_URL: ${IMDB_RATINGS_API_BASE_URL:-}
      IMDB_TAPFRAME_API_BASE_URL: ${IMDB_TAPFRAME_API_BASE_URL:-}
      AVATAR_PUBLIC_BASE_URL: ${AVATAR_PUBLIC_BASE_URL:-}
      UNIQUE_CONTRIBUTIONS_BASE_URL: ${UNIQUE_CONTRIBUTIONS_BASE_URL:-}
      DONATIONS_BASE_URL: ${DONATIONS_BASE_URL:-}
      DONATIONS_DONATE_URL: ${DONATIONS_DONATE_URL:-}
      SPONSOR_NAMES: ${SPONSOR_NAMES:-ragmehos.}
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID:-}
      SIMKL_CLIENT_ID: ${SIMKL_CLIENT_ID:-}
      SIMKL_APP_NAME: ${SIMKL_APP_NAME:-nuvio}
    ports:
      - "${NUVIO_PORT:-4173}:80"
    restart: unless-stopped
